<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Lab04</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>32b602c7-8b55-4f16-b38a-2d2add4171b3</testSuiteGuid>
   <testCaseLink>
      <guid>fc5eb3c6-4c69-4c99-b7f5-5c4925c52a31</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login_Success</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3093ef49-6bca-4b09-b1b5-1d73a7adff8e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2a4953d-9e60-4511-9707-469ae914dbc1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c75a7356-4cf0-4a8a-929a-9616c76db763</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login_Failed</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2a3d2a9-ad75-4ecb-b575-019f8dde298c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afefd110-5f30-4e03-927d-949adf855247</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
